name: Test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
          
      - name: Run tests
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover